### PR TITLE
fix: quite some patches

### LINKED ISSUE #128: singular subcommand
**Describe your new idea or enhancement**

credentials --> credential

### LINKED ISSUE #129: connection list to list all values
**Describe your new idea or enhancement**

see title

### LINKED ISSUE #130: add configuration environment
**Describe your new idea or enhancement**

see title

### LINKED ISSUE #131: get config path
**Describe your new idea or enhancement**

We currently have an option to set your config path, would it be a good addition if you could also get your config path. Needed it today and was confused that --config needed an input parameter as I thought it was to get the path. 

Screenshot from 2022-04-03 14-34-25

### LINKED ISSUE #132: required argument not mentioned in usage: --attributes in schemas/create
**Describe the bug**

Even though --attributes is a required flag on 

`aries-cli schemas create` 

It is not mentioned in the usage, resulting in an nunnecesary error message. 

**To Reproduce**

1. Run `aries-cli schemas create --name "College Degree"`

Screenshot from 2022-04-03 14-58-58

### LINKED ISSUE #133: aries-cli configuration view does not give output
**Describe the bug**

When I run `aries-cli configuration view` there is no output. 

**To Reproduce**

1. `aries-cli configuration view`

**Expected behavior**

A print of my current configuration file

**Aries CLI version (run `aries-cli --version`)**

0.2.0

**Desktop OS**
- OS: Linux
- Version:

**Verbose logs**

Run your command with the `-vvv` flag. See `aries-cli --help` for guidance.

<details>
  <summary>Logs</summary>

  ```
13:04:49 [DEBUG] aries_cli::register: [cli/src/register.rs:35] Parsed CLI options and initialized logger
13:04:49 [DEBUG] aries_cli::modules::configuration: [cli/src/modules/configuration.rs:42] Loaded configuration from /home/ana/.config/aries-cli/config.yaml
---
configurations:
  default:
    endpoint: "https://agent.communbobty.animo.id"
    api_key: ~

13:04:49 [DEBUG] aries_cli::register: [cli/src/register.rs:111] Successfully executed command

  ```

</details>
<br/>

**Screenshots, screen recordings**
If applicable.

**Additional context**

### LINKED ISSUE #134: clarify --attributes input
**Describe your new idea or enhancement**

Tried `aries-cli -c schemas create --name "College Degree" --attributes age name number`

This results in the error

 error: Found argument 'name' which wasn't expected, or isn't valid in this context

The option explanation does not mention how I should format multiple attributes in the attributes flag. Can this be clarified?

### LINKED ISSUE #135: Missing description from connections command
Missing descriptions for the --id option and receive subcommand from connections.

image

### LINKED ISSUE #136: propose credential not implemented description
Is this intentional? 

image

### LINKED ISSUE #137: Typo in aries-cli message
Should be `existing connection`

image

### PR DESCRIPTION
**Pull request by blu3beri**
closes #137 
closes #136 
closes #135 
closes #134 
closes #133 
closes #132 
closes #131 
closes #130 
closes #129 
closes #128

### CODE REVIEW

File: cloudagent-python/src/agent_python/agent.rs [hunk 1]
```diff
@@ -5,8 +5,8 @@ use agent::error::Result;
 /// TODO: How do we want to deal with mulitple versions? Architecture wise.
 #[derive(Debug)]
 pub enum CloudAgentPythonVersion {
-    /// ~0.6.0
-    ZeroSixZero,
+    /// ~0.7.3
```
Comment (morrieinmaas) [inline cloudagent-python/src/agent_python/agent.rs:8]: nice

**Review by morrieinmaas — COMMENTED** [review]
LGTM 🥳
