### PR TITLE
fix: renamed all workflow mentions to automation

### LINKED ISSUE #143: Rename workflow to automation in file paths for consistency.
**Describe your new idea or enhancement**

Even though we renamed the feature, the files and messages are still called workflow. (see workflow/src/workflows/credential_offer.rs)

I propose to change them for consistency. I started the process but didn't want to mess up anything.

### PR DESCRIPTION
**Pull request by blu3beri**
closes #143 

Signed-off-by: blu3beri <berend@animo.id>

### CODE REVIEW

File: cli/src/help_strings.rs [hunk 1]
```diff
@@ -169,12 +169,12 @@ impl HelpStrings {
             HelpStrings::ProofRequestPredicate => "Predicates required in the proof request (format = name,operator,value). e.g. -p=\"age,>=,18\"",
             HelpStrings::ProofRequestConnectionId => "Connection id to send the proof request to",
 
-            HelpStrings::Workflow => "Automated actions that combine multiple functions",
-            HelpStrings::WorkflowCredentialOffer => "Simple credential offer automation to offer a premade credential to any agent",
-            HelpStrings::WorkflowCredentialOfferConnectionId => "Connection id of the receiving party",
-            HelpStrings::WorkflowCredentialOfferNoQr => "Disables printing the qr code",
-            HelpStrings::WorkflowCredentialOfferSelf => "Completes the entire flow with itself",
-            HelpStrings::WorkflowCredentialOfferTimeout=> "Timeout for the entire flow in seconds",
+            HelpStrings::Automation => "Automated actions that combine multiple functions",
```
Comment (jloleysens) [inline cli/src/help_strings.rs:172]: Perhaps
```suggestion
            HelpStrings::Automation => "Run a set of actions against the agent",
```

File: cli/src/help_strings.rs [hunk 2]
```diff
@@ -169,12 +169,12 @@ impl HelpStrings {
...
+            HelpStrings::AutomationCredentialOffer => "Simple credential offer automation to offer a premade credential to any agent",
```
Comment (jloleysens) [inline cli/src/help_strings.rs:173]:
```suggestion
            HelpStrings::AutomationCredentialOffer => "Offer a premade credential to an agent",
```

File: cli/src/help_strings.rs [hunk 3]
```diff
@@ -169,12 +169,12 @@ impl HelpStrings {
...
+            HelpStrings::AutomationCredentialOfferConnectionId => "Connection id of the receiving party",
+            HelpStrings::AutomationCredentialOfferNoQr => "Disables printing the qr code",
+            HelpStrings::AutomationCredentialOfferSelf => "Completes the entire flow with itself",
```
Comment (jloleysens) [inline cli/src/help_strings.rs:176]:
```suggestion
            HelpStrings::AutomationCredentialOfferSelf => "Offer a credential to self",
```

File: cli/src/help_strings.rs [hunk 4]
```diff
@@ -169,12 +169,12 @@ impl HelpStrings {
...
+            HelpStrings::AutomationCredentialOfferTimeout=> "Timeout for the entire flow in seconds",
```
Comment (jloleysens) [inline cli/src/help_strings.rs:177]:
```suggestion
            HelpStrings::AutomationCredentialOfferTimeout=> "Timeout in seconds",
```

File: cli/src/help_strings.rs [hunk 5]
```diff
@@ -169,12 +169,12 @@ impl HelpStrings {
...
-            HelpStrings::Workflow => "Automated actions that combine multiple functions",
-            HelpStrings::WorkflowCredentialOffer => "Simple credential offer automation to offer a premade credential to any agent",
-            HelpStrings::WorkflowCredentialOfferConnectionId => "Connection id of the receiving party",
-            HelpStrings::WorkflowCredentialOfferNoQr => "Disables printing the qr code",
-            HelpStrings::WorkflowCredentialOfferSelf => "Completes the entire flow with itself",
-            HelpStrings::WorkflowCredentialOfferTimeout=> "Timeout for the entire flow in seconds",
+            HelpStrings::Automation => "Automated actions that combine multiple functions",
+            HelpStrings::AutomationCredentialOffer => "Simple credential offer automation to offer a premade credential to any agent",
+            HelpStrings::AutomationCredentialOfferConnectionId => "Connection id of the receiving party",
+            HelpStrings::AutomationCredentialOfferNoQr => "Disables printing the qr code",
```
Comment (jloleysens) [inline cli/src/help_strings.rs:175]:
```suggestion
            HelpStrings::AutomationCredentialOfferNoQr => "Do not show a QR code",
```

**Review by jloleysens — APPROVED** [review]
I've left comments about copy improvements that I'd like to see added before merging. Approving to unblock!

I still believe `automate` is a little bit strange compared to other verbs like `execute` or `run`, but I am happy we have something we are moving forward with!
